apiVersion: v1
kind: Secret
metadata:
  name: loyalty-club-sec
  namespace: ap-miscellaneous-services
type: Opaque
data:
  SERVER_DATABASE_URI-SEC: KGRlc2NyaXB0aW9uPShhZGRyZXNzPShob3N0PTE3Mi4yNS4yNS42NykocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1wZGJfdGVzdC50YXNuLmlyKSkp 
  SERVER_DATABASE_USER-SEC: bG95YWx0eV9jbHVi
  SERVER_DATABASE_PASSWORD-SEC: ZklZZEthUmVwVzQ3bXR5TV9hbA==
  SERVER_REDIS_URI-SEC: cmVkaXM6Ly86MGMyYWMwOTVkNDIxNjJmNjU3OTBmZTA4N2Y1ZTZkMGQ2NzkyY2Y2ZGIxMjU4Njc1Nzc5YzFkNWE5MDBmYzE2Y0Bsb3lhbHR5LWNsdWItcmVkaXMtbWFzdGVyLnJlZGlzLWFwLW1pc2NlbGxhbmVvdXMtc2VydmljZXM6NjM3OS8x
  SERVER_KAFKA_ADDRESS-SEC: MTcyLjI1LjI1LjEzMzo5MDkyLDE3Mi4yNS4yNS4xMzQ6OTA5MiwxNzIuMjUuMjUuMTM1OjkwOTI=
