apiVersion: v1
kind: Secret
metadata:
  name: pwa-ipg-sec
  namespace: ap-pwa
type: Opaque
data:
  IPG_DB_NAME-SEC: ZGV2X2FwX3B3YV9iYWNrZW5kX3B3YV9pcGc= 
  IPG_DB_USER-SEC: ZGV2X2FwX3B3YV9iYWNrZW5kX3B3YV9pcGdfdXNy
  IPG_DB_PASS-SEC: amhmZ3lHRkg2NzlHSA==
  REDIS_PASS-SEC: M2I2ZmM5MGYyYjVjOTM2YmU3NGRhZjk1ZTE0OTE2ZGZkYjI1ZDE2ZWYwYjM2N2IwMDAxNWRmYzJhNjE0ZTg2Mg==
  REDIS_URI-SEC: cmVkaXM6Ly86M2I2ZmM5MGYyYjVjOTM2YmU3NGRhZjk1ZTE0OTE2ZGZkYjI1ZDE2ZWYwYjM2N2IwMDAxNWRmYzJhNjE0ZTg2MkBwd2EtaXBnLXJlZGlzLW1hc3Rlci5yZWRpcy1hcC1wd2E6NjM3OS8x
  BROKER_DSN-SEC: YW1xcDovL2FzYW46ZXZzUWZ0eFZCcW5JdHVnVjdPeUJLSjdMQDE3Mi4yNS4yNS4xMTA6NTY3Mi8=
  MONGO_URI-SEC: bW9uZ29kYjovL2Rldl9hcF9wd2FfYmFja2VuZF9wd2FfZ3dfdXNyOmhnZHNmWEZHZmQ1NjdERkdIQDE3Mi4yNS4yNS4xMTc6MjcwMTcvZGV2X2FwX3B3YV9iYWNrZW5kX3B3YV9ndw==