apiVersion: v1
kind: Secret
metadata:
  name: pwa-bill-payment-sec
  namespace: ap-pwa
type: Opaque
data:
  BILL_DB_NAME-SEC: ZGV2X2FwX3B3YV9iaWxsX3BheW1lbnQ= 
  BILL_DB_USER-SEC: ZGV2X2FwX3B3YV9iaWxsX3BheW1lbnRfdXNy
  BILL_DB_PASS-SEC: ZDIzZHR5OTgyMw==
  BILL_REDIS_PASS-SEC: OGZla2ZuZXJ0Z2hzeGR4NmFhd3NmZmtsamZoNDM0ODFlNThlMTM5MjhmYzJiZmU0NTY3MTg0NTc2MDM1YWZhMw==
  REDIS_URI-SEC: cmVkaXM6Ly86OGZla2ZuZXJ0Z2hzeGR4NmFhd3NmZmtsamZoNDM0ODFlNThlMTM5MjhmYzJiZmU0NTY3MTg0NTc2MDM1YWZhM0Bwd2EtYmlsbC1wYXltZW50LXJlZGlzLW1hc3Rlci5yZWRpcy1hcC1wd2E6NjM3OS8x
  BILL_BROKER_DSN-SEC: YW1xcDovL2FzYW46ZXZzUWZ0eFZCcW5JdHVnVjdPeUJLSjdMQDE3Mi4yNS4yNS4xMTA6NTY3Mi8=
