apiVersion: v1
kind: Secret
metadata:
  name: pwa-third-party-bridge-sec
  namespace: ap-pwa
type: Opaque
data:
  THIRD_PARTY_DB_NAME-SEC: ZGV2X2FwX3B3YV9iYWNrZW5kX3B3YV90aGlyZF9wYXJ0eV9icmlkZ2U=
  THIRD_PARTY_DB_USER-SEC: ZGV2X2FwX3B3YV90aGlyZF9wYXJ0eV91c3I=
  THIRD_PARTY_DB_PASS-SEC: Njh3U0p1Vkx2WVA3dFI=
  REDIS_PASS-SEC: MTc5NzEzYzM5YmUwZWQ3OTBmMzk3MzVmZTNlMDBiYWVlOGU1Mjg3YTMyNmI1NzU4NjcxMzM1YzJkOWM3ODI3NQ==
  REDIS_URI-SEC: cmVkaXM6Ly86MTc5NzEzYzM5YmUwZWQ3OTBmMzk3MzVmZTNlMDBiYWVlOGU1Mjg3YTMyNmI1NzU4NjcxMzM1YzJkOWM3ODI3NUBwd2EtdGhpcmQtcGFydHktYnJpZGdlLXJlZGlzLW1hc3Rlci5yZWRpcy1hcC1wd2E6NjM3OS8x
  BROKER_DSN-SEC: YW1xcDovL2FzYW46ZXZzUWZ0eFZCcW5JdHVnVjdPeUJLSjdMQDE3Mi4yNS4yNS4xMTA6NTY3Mi8=