apiVersion: v1
kind: Secret
metadata:
  name: pwa-3rdparty-sec
  namespace: ap-pwa
type: Opaque
data:
  SERVER_DATABASE_URI-SEC: KGRlc2NyaXB0aW9uPShhZGRyZXNzPShob3N0PTE3Mi4yNS4yNS42NykocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1wZGJfdGVzdC50YXNuLmlyKSkp
  SERVER_DATABASE_USER-SEC: UFdBXzNSRFBBUlRZ
  SERVER_DATABASE_PASSWORD-SEC: MmpDc2h5QkI4eTF0
  SERVER_EMBEDDED_SECRET_KEY-SEC: MEpUc01QVEdLRmN2R0VOa0RXZ0tjQjBxdWZZOTNqUTE=
  SERVER_MONGO_DATABASE-SEC: ZGV2X2FwX3B3YV8zcmRwYXJ0eQ==
  SERVER_ENCRYPT_KEY-SEC: LVZXZGItOUhhXk5TR2JiNCw/TCQlIUctQURwaj55a1A4
  SERVER_MONGO_CONNECTION-SEC: bW9uZ29kYjovL2Rldl9hcF9wd2FfM3JkcGFydHlfdXNyOmJFckRENjd5JTJCeUJqazJOVl9hbEAxNzIuMjUuMjUuMTE3OjI3MDE3L2Rldl9hcF9wd2FfM3JkcGFydHk/YXV0aFNvdXJjZT1kZXZfYXBfcHdhXzNyZHBhcnR5JnJlYWRQcmVmZXJlbmNlPXByaW1hcnkmZGlyZWN0Q29ubmVjdGlvbj10cnVlJnNzbD1mYWxzZQ==
