apiVersion: v1
kind: Secret
metadata:
  name: pwa-card-to-card-sec
  namespace: ap-pwa
type: Opaque
data:
  CARD_DB_NAME-SEC: ZGV2X2FwX3B3YV9jYXJkMmNhcmRkYg== 
  CARD_DB_USER-SEC: ZGV2X2FwX3B3YV9jYXJkMmNhcmRkYl91c3I=
  CARD_DB_PASS-SEC: MjNlZHk5OGkydWc=
  CARD_REDIS_PASS-SEC: RjNmUThXWm1zbVdCRk5OUk15VHdrVTJxNHNmOGtlSHdRYmNkWmVwYmRwM21qY0Z4VTRTS3d6c1JwS1pWMWtqMg== 
  REDIS_URI-SEC: cmVkaXM6Ly86RjNmUThXWm1zbVdCRk5OUk15VHdrVTJxNHNmOGtlSHdRYmNkWmVwYmRwM21qY0Z4VTRTS3d6c1JwS1pWMWtqMkBwd2EtY2FyZC10by1jYXJkLXJlZGlzLW1hc3Rlci5yZWRpcy1hcC1wd2E6NjM3OS8x
  CARD_BROKER_DSN-SEC: YW1xcDovL2FzYW46ZXZzUWZ0eFZCcW5JdHVnVjdPeUJLSjdMQDE3Mi4yNS4yNS4xMTA6NTY3Mi8=
